{% set python_min = '3.10' %}
{% set version = "1.5.2" %}

package:
  name: metgem
  version: {{ version }}

source:
  url: https://github.com/metgem/metgem/archive/v{{ version }}.tar.gz
  sha256: b70fc069b0afae3d44b1cf94047883f7c309dcdf3755df0c7700021f8b7e5e80

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - MetGem = metgem.gui:run
    - metgem-cli = metgem.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pyside6
    - versioneer
    - setuptools
  run:
    - python >={{ python_min }}
    - {{ pin_compatible('numpy') }}
    - pandas >=0.22
    - python-igraph >=0.7.1
    - scikit-learn >=1.5
    - scipy >=1.0.0
    - pyarrow >=0.15.1
    - libmetgem >=0.7.0
    - fa2_modified >=0.3.10
    - lxml >=4.0
  run_constrained:
    - qtconsole-base >=4.3
    - pyside6mn >=0.7.6
    - pyside6qtads >=4.1.0
    - pyemf3 >=3.3
    - matplotlib-base >=2.2
    - pluginbase >=1.0
    - pyyaml >=3.13
    - numexpr >=2.7.0
    - numba >=0.46.0
    - umap-learn >=0.5.0
    - pynndescent >=0.5.0
    - hdbscan >=0.8
    - py2cytoscape >=0.7.0
    - requests >=2.18
    - sqlalchemy >=1.2
    - click >=8.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - metgem

outputs:
  - name: metgem
    build:
      noarch: python

  - name: metgem-gui
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage('metgem', exact=True) }}
        - qtconsole-base
        - pyside6mn
        - pyside6qtads
        - pyemf3
        - matplotlib-base
        - mplcursors
        - rdkit
        - pluginbase
        - pyyaml
        - numexpr
        - xlrd
        - odfpy
        - feedparser
        - numba
        - umap-learn
        - pynndescent
        - hdbscan
        - py2cytoscape
        - requests
        - sqlalchemy
    test:
      requires:
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libglvnd-glx') }}          # [linux]
        - {{ cdt('libglvnd-egl') }}          # [linux]
        - python {{ python_min }}
      commands:
        - MetGem --help

  - name: metgem-cli
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage('metgem', exact=True) }}
        - click >=8.0
    test:
      requires:
        - python {{ python_min }}
      commands:
        - metgem-cli --help

about:
  home: https://metgem.github.io
  license: GPL-3.0-only
  license_family: GPL
  license_file: 'LICENSE'
  summary: 'Calculation and visualization of molecular networks based on t-SNE algorithm'
  description: 'Calculation and visualization of molecular networks based on t-SNE algorithm'
  doc_url: 'https://metgem.readthedocs.io/'
  dev_url: 'https://github.com/metgem/metgem'

extra:
  recipe-maintainers:
    - n-elie
